# Generated by Django 3.2.3 on 2021-06-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210602_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ('Продукт',), 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': ('Категория',), 'verbose_name_plural': 'Категории'},
        ),
    ]
